import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/Providers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <ul className=" flex justify-center gap-8 py-5">
              <li className=" bg-orange-700 py-2 px-5 rounded-md shadow-lg text-white"> <Link href={'/'} >Product</Link> </li>
              <li className=" bg-orange-700 py-2 px-5 rounded-md shadow-lg text-white"> <Link href={'/cart'} >Cart</Link> </li>
            </ul>
          </div>
          <div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
